### ISSUE TITLE
Clarification needed: multiple gsheet tabs

### ISSUE THREAD

**Issue by EskoBrummel** [suryajasper/Food-Bank-Smart-Routes#15]
Surya had explained how to avoid multiple tabs being created by the program by refreshing the page before rerunning the program. Just so I understand, if I'm not happy with the initial calculation and want to change the parameters I need to first refresh the page then change parameters and hit calculate again for it to work without creating multiple tabs? Thanks

**Comment by suryajasper** [comment]
Fixed bug. no need to refresh anymore

**Comment by suryajasper** [comment]
Fixed bug. no need to refresh anymore
